# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
daily_exp_interval_cpp <- function(growth, tmax, t0) {
    .Call('_covback_daily_exp_interval_cpp', PACKAGE = 'covback', growth, tmax, t0)
}

calculate_infection_incidence <- function(growth_rate, growth_rate_imports, tmax, t0, t0_import, i0, import_propn, imports_stop) {
    .Call('_covback_calculate_infection_incidence', PACKAGE = 'covback', growth_rate, growth_rate_imports, tmax, t0, t0_import, i0, import_propn, imports_stop)
}

calculate_onset_incidence <- function(infections, weibull_alpha, weibull_sigma, tmax) {
    .Call('_covback_calculate_onset_incidence', PACKAGE = 'covback', infections, weibull_alpha, weibull_sigma, tmax)
}

calculate_confirmation_incidence <- function(onsets, shapes, scales, tmax) {
    .Call('_covback_calculate_confirmation_incidence', PACKAGE = 'covback', onsets, shapes, scales, tmax)
}

calculate_all_incidences <- function(growth_rate, growth_rate_imports, t0, t0_import, i0, import_propn, imports_stop, weibull_alpha, weibull_sigma, shapes, scales, tmax) {
    .Call('_covback_calculate_all_incidences', PACKAGE = 'covback', growth_rate, growth_rate_imports, t0, t0_import, i0, import_propn, imports_stop, weibull_alpha, weibull_sigma, shapes, scales, tmax)
}

